# Quantile delta mapping configuration

## User configured variables

METHOD=qdm
SCALING=multiplicative
#GROUPING=
GROUPING=--time_grouping monthly
OUTPUT_UNITS="mm day-1"
SSR=--ssr
MEAN_MATCH_TIMESCALE=monthly
INTERP=nearest
REF_TIME=--ref_time

MODEL=ACCESS-ESM1-5
RUN=r1i1p1f1
#RUN=r6i1p1f1
HIST_VERSION=v20191115
REF_VERSION=v20191115
MODEL_GRID=gn
NCI_LOC=fs38/publications

#MODEL=ACCESS-CM2
#RUN=r4i1p1f1
#HIST_VERSION=v20210607
#REF_VERSION=v20210712
#MODEL_GRID=gn
#NCI_LOC=fs38/publications

OBS_DATASET=AGCD
TARGET_VAR=precip
TARGET_UNITS="mm day-1"
TARGET_START=1990
TARGET_END=2019

EXPERIMENT=ssp370

HIST_VAR=pr
HIST_UNITS="kg m-2 s-1"
HIST_START=1995
HIST_END=2014

REF_VAR=pr
REF_UNITS="kg m-2 s-1"
REF_START=2056
REF_END=2085

## Automatic variables

HIST_DATA := $(sort $(wildcard /g/data/${NCI_LOC}/CMIP6/CMIP/*/${MODEL}/historical/${RUN}/day/${HIST_VAR}/${MODEL_GRID}/${HIST_VERSION}/*.nc))
REF_DATA := $(sort $(wildcard /g/data/${NCI_LOC}/CMIP6/ScenarioMIP/*/${MODEL}/${EXPERIMENT}/${RUN}/day/${REF_VAR}/${MODEL_GRID}/${REF_VERSION}/*.nc))
TARGET_DATA := $(wildcard /g/data/xv83/agcd-csiro/${TARGET_VAR}/daily/*_AGCD-CSIRO_r005_*_daily_space-chunked.zarr)

OUTPUT_HIST_DIR=/g/data/wp00/data/QQ-CMIP6/${MODEL}/historical/${RUN}/day/${HIST_VAR}/${HIST_VERSION}
OUTPUT_REF_DIR=/g/data/wp00/data/QQ-CMIP6/${MODEL}/${EXPERIMENT}/${RUN}/day/${REF_VAR}/${REF_VERSION}
OUTPUT_TARGET_DIR=/g/data/wp00/data/${OBS_DATASET}

AF_FILE=${REF_VAR}-${METHOD}-${SCALING}-monthly-q100-ssr-adjustment-factors_${MODEL}_${EXPERIMENT}_${RUN}_${MODEL_GRID}_${REF_START}0101-${REF_END}1231_wrt_${HIST_START}0101-${HIST_END}1231.nc
AF_PATH=${OUTPUT_REF_DIR}/${AF_FILE}

QQ_BASE=${REF_VAR}_day_${MODEL}_${EXPERIMENT}_${RUN}_AUS-r005_${REF_START}0101-${REF_END}1231_${METHOD}-${SCALING}-monthly-q100-${INTERP}-ssr_${OBS_DATASET}-${TARGET_START}0101-${TARGET_END}1231_historical-${HIST_START}0101-${HIST_END}1231
QQ_PATH=${OUTPUT_REF_DIR}/${QQ_BASE}.nc

VALIDATION_NOTEBOOK=${OUTPUT_REF_DIR}/${QQ_BASE}.ipynb


