# NPCP bias correction configuration

## User configured variables

TASK=historical
METHOD=ecdfm
INTERP=nearest
GROUPING=--time_grouping monthly

## Temperature 
#SCALING=additive
#OUTPUT_UNITS=C
#HIST_VAR=tasmin
#HIST_UNITS_ORIG=C
#REF_VAR=tasmin
#REF_UNITS_ORIG=C
#TARGET_VAR=tasmin
#TARGET_UNITS_ORIG=C

# Precip 
SCALING=multiplicative
OUTPUT_UNITS="mm day-1"
HIST_VAR=pr
HIST_UNITS_ORIG="mm day-1"
REF_VAR=pr
REF_UNITS_ORIG="mm day-1"
TARGET_VAR=pr
TARGET_UNITS_ORIG="mm day-1"
SSR=--ssr

OBS_DATASET=AGCD
GCM_NAME=ECMWF-ERA5
GCM_RUN=r1i1p1f1
RCM_NAME=BOM-BARPA-R
RCM_VERSION=v1
EXPERIMENT=evaluation

HIST_START=1980
HIST_END=1999
REF_START=1980
REF_END=1999
TARGET_START=2000
TARGET_END=2019


## Automatic variables
HIST_PATH=/g/data/ia39/npcp/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/raw/task-reference
TARGET_PATH=/g/data/ia39/npcp/data/${TARGET_VAR}/${GCM_NAME}/${RCM_NAME}/raw/task-reference
REF_PATH=/g/data/ia39/npcp/data/${REF_VAR}/observations/${OBS_DATASET}/raw/task-reference

HIST_FILES_ORIG := $(sort $(wildcard ${HIST_PATH}/*day_19*.nc))
TARGET_FILES_ORIG := $(sort $(wildcard ${TARGET_PATH}/*day_20*.nc))
REF_FILES_ORIG := $(sort $(wildcard ${REF_PATH}/*.nc))

OUTPUT_HIST_DIR=/g/data/xv83/dbi599/npcp/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}/task-${TASK}
OUTPUT_REF_DIR=/g/data/xv83/dbi599/npcp/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}/task-${TASK}
OUTPUT_TARGET_DIR=/g/data/xv83/dbi599/npcp/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}/task-${TASK}
#ifeq (${SSR}, --ssr)
#HIST_DATA=${OUTPUT_HIST_DIR}/${HIST_VAR}-ssr_NPCP-20i_${GCM_NAME}_${EXPERIMENT}_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${HIST_START}01-${HIST_END}12.nc
#HIST_UNITS=${OUTPUT_UNITS}
#REF_DATA=${OUTPUT_REF_DIR}/${REF_VAR}-ssr_NPCP-20i_${OBS_DATASET}_v1_day_${REF_START}01-${REF_END}12.nc
#REF_UNITS=${OUTPUT_UNITS}
#REF_FNAME_VAR=${REF_VAR}-ssr
#TARGET_DATA=${OUTPUT_HIST_DIR}/${HIST_VAR}-ssr_NPCP-20i_${GCM_NAME}_${EXPERIMENT}_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${TARGET_START}01-${TARGET_END}12.nc
#TARGET_UNITS=${OUTPUT_UNITS}
#TARGET_FNAME_VAR=${TARGET_VAR}-ssr
#else
HIST_DATA=${HIST_FILES_ORIG}
HIST_UNITS=${HIST_UNITS_ORIG}
REF_DATA=${REF_FILES_ORIG}
REF_UNITS=${REF_UNITS_ORIG}
REF_FNAME_VAR=${REF_VAR}
TARGET_DATA=${TARGET_FILES_ORIG}
TARGET_UNITS=${TARGET_UNITS_ORIG}
TARGET_FNAME_VAR=${TARGET_VAR}
#endif

AF_FILE=${REF_FNAME_VAR}-${METHOD}-${SCALING}-monthly-q100-ssr-adjustment-factors_${OBS_DATASET}_NPCP-20i_${GCM_NAME}_${EXPERIMENT}_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${HIST_START}01-${HIST_END}12.nc
AF_PATH=${OUTPUT_REF_DIR}/${AF_FILE}

QQ_BASE=${REF_FNAME_VAR}_NPCP-20i_${GCM_NAME}_${EXPERIMENT}_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${TARGET_START}01-${TARGET_END}12_${METHOD}-${SCALING}-monthly-q100-${INTERP}-ssr-${OBS_DATASET}-${HIST_START}01-${HIST_END}12
QQ_PATH=${OUTPUT_REF_DIR}/${QQ_BASE}.nc

VALIDATION_NOTEBOOK=${OUTPUT_REF_DIR}/${QQ_BASE}.ipynb


