# Quantile mapping bias adjustment configuration

## User configured variables

METHOD=qmba
SCALING=additive
OUTPUT_UNITS=C
#SSR=--ssr

OBS_DATASET=AGCD
MODEL=ECMWF-ERA5
EXPERIMENT=evaluation

HIST_VAR=tasmin
HIST_UNITS_ORIG=C
HIST_START=1980
HIST_END=1999

REF_VAR=tasmin
REF_UNITS_ORIG=C
REF_START=1980
REF_END=1999

TARGET_VAR=tasmin
TARGET_UNITS_ORIG=C
TARGET_START=2000
TARGET_END=2019

# (Omeo)
EXAMPLE_LAT = -37.1
EXAMPLE_LON = 147.6
EXAMPLE_MONTH = 5

## Automatic variables
HIST_PATH=/g/data/ia39/npcp/data/${HIST_VAR}/ECMWF-ERA5/BOM-BARPA-R/raw
TARGET_PATH=/g/data/ia39/npcp/data/${TARGET_VAR}/ECMWF-ERA5/BOM-BARPA-R/raw
REF_PATH=/g/data/ia39/npcp/data/${REF_VAR}/observations/AGCD/raw

HIST_FILES_ORIG := $(sort $(wildcard ${HIST_PATH}/*day_19*.nc))
TARGET_FILES_ORIG := $(sort $(wildcard ${TARGET_PATH}/*day_20*.nc))
REF_FILES_ORIG := $(sort $(wildcard ${REF_PATH}/*day_19*.nc))

OUTPUT_HIST_DIR=/g/data/ia39/npcp/data/${HIST_VAR}/ECMWF-ERA5/BOM-BARPA-R/qm
OUTPUT_REF_DIR=/g/data/ia39/npcp/data/${HIST_VAR}/ECMWF-ERA5/BOM-BARPA-R/qm
OUTPUT_TARGET_DIR=/g/data/ia39/npcp/data/${HIST_VAR}/ECMWF-ERA5/BOM-BARPA-R/qm
ifeq (${SSR}, --ssr)
HIST_DATA=${OUTPUT_HIST_DIR}/${HIST_VAR}-ssr_NPCP-20i_ECMWF-ERA5_evaluation_r1i1p1f1_BOM-BARPA-R_v1_day_${HIST_START}01-${HIST_END}12.nc
HIST_UNITS=${OUTPUT_UNITS}
REF_DATA=${OUTPUT_REF_DIR}/${REF_VAR}-ssr_NPCP-20i_${OBS_DATASET}_v1_day_${REF_START}01-${REF_END}12.nc
REF_UNITS=${OUTPUT_UNITS}
REF_FNAME_VAR=${REF_VAR}-ssr
TARGET_DATA=${OUTPUT_HIST_DIR}/${HIST_VAR}-ssr_NPCP-20i_ECMWF-ERA5_${EXPERIMENT}_r1i1p1f1_BOM-BARPA-R_v1_day_${TARGET_START}01-${TARGET_END}12.nc
TARGET_UNITS=${OUTPUT_UNITS}
TARGET_FNAME_VAR=${TARGET_VAR}-ssr
else
HIST_DATA=${HIST_FILES_ORIG}
HIST_UNITS=${HIST_UNITS_ORIG}
REF_DATA=${REF_FILES_ORIG}
REF_UNITS=${REF_UNITS_ORIG}
REF_FNAME_VAR=${REF_VAR}
TARGET_DATA=${TARGET_FILES_ORIG}
TARGET_UNITS=${TARGET_UNITS_ORIG}
TARGET_FNAME_VAR=${TARGET_VAR}
endif

AF_FILE=${REF_FNAME_VAR}-${METHOD}-${SCALING}-monthly-bias-vs-${OBS_DATASET}_NPCP-20i_ECMWF-ERA5_evaluation_r1i1p1f1_BOM-BARPA-R_v1_day_${HIST_START}01-${HIST_END}12.nc
AF_PATH=${OUTPUT_REF_DIR}/${AF_FILE}

TARGET_Q_FILE=${TARGET_FNAME_VAR}-quantiles_NPCP-20i_ECMWF-ERA5_${EXPERIMENT}_r1i1p1f1_BOM-BARPA-R_v1_day_${TARGET_START}01-${TARGET_END}12.nc
TARGET_Q_PATH=${OUTPUT_TARGET_DIR}/${TARGET_Q_FILE}

QQ_BASE=${REF_FNAME_VAR}_NPCP-20i_ECMWF-ERA5_${EXPERIMENT}_r1i1p1f1_BOM-BARPA-R_v1_day_${TARGET_START}01-${TARGET_END}12_${METHOD}-${SCALING}-monthly-${OBS_DATASET}-${HIST_START}01-${HIST_END}12
QQ_PATH=${OUTPUT_REF_DIR}/${QQ_BASE}.nc

VALIDATION_NOTEBOOK=${OUTPUT_REF_DIR}/${QQ_BASE}.ipynb


