# NPCP precipication bias correction configuration

## User configured variables

METHOD=ecdfm
INTERP=nearest
GROUPING=--time_grouping monthly
SCALING=additive
OUTPUT_GRID=af

OUTPUT_UNITS=C
HIST_VAR=tasmin
HIST_UNITS=K
REF_VAR=tmin
REF_UNITS=C
TARGET_VAR=tasmin
TARGET_UNITS=K

OBS_DATASET=AGCD
RCM_VERSION=v1

#RCM_NAME=UQ-DES-CCAM-2105
RCM_NAME=BOM-BARPA-R

GCM_NAME=CSIRO-ACCESS-ESM1-5
GCM_RUN=r6i1p1f1
EXPERIMENT=ssp370

## Automatic variables

ifeq (${RCM_NAME}, UQ-DES-CCAM-2105)
NO_LEAP_TRAINING=--no_leap
endif

CORDEX_PATH=/g/data/ia39/australian-climate-service/release/CORDEX-CMIP6/output
HIST_PATH=${CORDEX_PATH}/AUS-15/BOM/${GCM_NAME}/historical/${GCM_RUN}/${RCM_NAME}/v1/day/${HIST_VAR}
TARGET_PATH=${CORDEX_PATH}/AUS-15/BOM/${GCM_NAME}/${EXPERIMENT}/${GCM_RUN}/${RCM_NAME}/v1/day/${TARGET_VAR}

HIST_START=1985
HIST_END=2014
HIST_DATA := $(sort $(wildcard ${HIST_PATH}/*day_198[5,6,7,8,9]*.nc) $(wildcard ${HIST_PATH}/*day_199*.nc) $(wildcard ${HIST_PATH}/*day_2*.nc))
REF_START=1985
REF_END=2014
REF_DATA := $(wildcard /g/data/xv83/agcd-csiro/${REF_VAR}/daily/*_AGCD-CSIRO_r005_*_daily_space-chunked.zarr)
TARGET_START=2030
TARGET_END=2059
TARGET_DATA := $(sort $(wildcard ${HIST_PATH}/*.nc) $(wildcard ${TARGET_PATH}/*.nc))
OUTPUT_START=2040
OUTPUT_END=2049
OUTPUT_TSLICE=--output_tslice ${OUTPUT_START}-01-01 ${OUTPUT_END}-12-31

TRAINING_DATES=${HIST_START}0101-${HIST_END}1231
ADJUSTMENT_DATES=${TARGET_START}0101-${TARGET_END}1231
OUTPUT_DATES=${OUTPUT_START}0101-${OUTPUT_END}1231

OUTPUT_AF_DIR=/g/data/xv83/dbi599/acs/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}
OUTPUT_QQ_DIR=/g/data/xv83/dbi599/acs/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}
OUTPUT_VALIDATION_DIR=/g/data/xv83/dbi599/acs/data/${HIST_VAR}/${GCM_NAME}/${RCM_NAME}/${METHOD}

AF_FILE=${TARGET_VAR}-${METHOD}-${SCALING}-monthly-q100-adjustment-factors_${OBS_DATASET}_AUS-05i_${GCM_NAME}_historical_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${TRAINING_DATES}.nc
AF_PATH=${OUTPUT_AF_DIR}/${AF_FILE}

QQ_BASE=${TARGET_VAR}_AUS-05i_${GCM_NAME}_${EXPERIMENT}_${GCM_RUN}_${RCM_NAME}_${RCM_VERSION}_day_${OUTPUT_DATES}-from-${ADJUSTMENT_DATES}_${METHOD}-${SCALING}-monthly-q100-${INTERP}-${OBS_DATASET}-${TRAINING_DATES}

QQ_PATH=${OUTPUT_QQ_DIR}/${QQ_BASE}.nc

VALIDATION_NOTEBOOK=${OUTPUT_VALIDATION_DIR}/${QQ_BASE}.ipynb

